apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: pi
        image: python
        command: ["python",  "import pandas as pd"]
        terminationMessagePath: "/tmp/my-log"
        terminationMessagePolicy: "FallbackToLogsOnError"
      restartPolicy: OnFailure
  backoffLimit: 4
